DOV-Vlaanderen/pydov

CONTRIBUTING.md
README.md
accessing_dov_data.md

I added some documentation regarding the various service endpoints that we provide and that can be used to search through metadata and view and download the data we publish.
Please feel free to enhance or extend where needed, or to ask questions if some things are still unclear.

Added some documentation of DOV service endpoints

---

accessing_dov_data.md

We published feature catalogues of the layers with boringen (boreholes) and sonderingen (CPT's), so I added them to the table.

Added links to feature catalogues of boringen and sonderingen.

---

README.rst
appveyor.yml

Add AppVeyor

---

docs/description_output_dataframes.rst
docs/usage.rst

discussion note on output of interpretations and boreholes

---

docs/description_output_dataframes.rst

Describe your fixes/additions/changes

add 'boornummer' for the ease of use by experts

---

docs/_static/css/custom.css
docs/_templates/layout.html
docs/conf.py

Make sure the template is wider on the user screen, as requested

Use full page width for rtd theme

---

docs/_static/css/custom.css

Thanks to @peterdesmet for the nice tip to improve the sphinx rtd theme

Add word wrapping to theme

---

docs/description_output_dataframes.rst

Added source (wfs/xml) to the output dataframes description.

Add source (wfs/xml) to the output dataframes description

---

.travis.yml
appveyor.yml
tox.ini

Since we use either the integrated XML parsing of Python or the one
provided by the 'lxml' library, it is best to run our tests in both
setups. Especially since lxml supports additional functionality, so we
have to make sure not to rely on this in the code.

Add lxml environment to CI

---

pydov/search.py
pydov/util/owsutil.py
tests/test_search.py
tests/test_types_boring.py
tests/test_util_owsutil.py

I added some extra tests based on the coveralls report.

Add some extra tests.

---

examples/boring_search.py
pydov/search/abstract.py
pydov/search/boring.py
tests/test_search.py

Move search to its own package.

---

docs/description_output_dataframes.rst

A layout of data from sonderingen in the docs

Add docs df sonderingen

---

docs/notebooks/.ipynb_checkpoints/example_search_boringen-checkpoint.ipynb
docs/notebooks/example_search_boringen.ipynb
requirements.txt

A first example notebook on search for 'boringen'

Notebook examples

---

binder/requirements.txt
docs/conf.py
docs/index.rst
docs/notebooks/example_search_boringen.ipynb
docs/notebooks/example_search_grondwaterfilters.ipynb
docs/tutorials.rst
requirements_dev.txt
requirements_doc.txt

Further adjustments to the sphinx notebook handling towards separate tutorials pages with binder link

Sphinx notebooks

---

requirements_dev.txt
setup.py
tests/test_encoding.py
tests/test_util_caching.py
tests/test_util_hooks.py

Fixes #94 on the Appveyor build

Fix #94 by adding requirements

---

appveyor.yml

Previously the lxml install command was only printed out to the terminal instead of actually being called.

Appveyor: actually install lxml instead of printing the install command

---

docs/endpoints.rst

Fix link to DOV XML documentation.

Fix link to DOV XML documentation.

---

.travis.yml
pydov/search/abstract.py
tests/abstract.py
tox.ini

Indicate whether fields can be used in attribute queries.

Indicate whether fields can be used in attribute queries.

---

pydov/util/owsutil.py

This warning is irrelevant for pydov users.

Hide FutureWarning from OWSLib MD_Metadata.

---

docs/tutorials.rst

small PR to make sure the tutorial about `formele stratigrafie` is added to the tutorials overview

Add tutorial form strat in index

---

README.md
docs/index.rst

Add reference to DOV disclaimer.
Closes #139

Add reference to DOV disclaimer.

---

.travis.yml

Fix travis pypi passwd

---

pydov/search/grondwaterfilter.py
pydov/types/abstract.py
tests/abstract.py

Exclude putten without filters from the results of GrondwaterFilterSearch.
Closes #161

Fix GrondwaterFilter for putten without filters

---

docs/query_attribute.rst
pydov/util/query.py
tests/test_util_query.py

Support Join queries where the column name in the dataframe is different from the one in the type being searched.
Closes #152

Support joins using a different column name

---

.travis.yml

Describe your fixes/additions/changes

Add coveralls webhook to travis

---

pydov/__init__.py
pydov/search/abstract.py
pydov/types/abstract.py
pydov/types/boring.py
pydov/types/grondwaterfilter.py
pydov/types/interpretaties.py
pydov/types/sondering.py
pydov/util/hooks.py
pydov/util/location.py
pydov/util/owsutil.py
pydov/util/query.py
tests/data/update_test_data.py

Update to string formatting using the .format() function.
There should be no impact on existing implementations or use-cases.

Update to 'new'-style string formatting

---

docs/output_fields.rst
pydov/search/abstract.py
pydov/search/boring.py
pydov/search/grondwaterfilter.py
pydov/search/interpretaties.py
pydov/search/sondering.py
pydov/util/owsutil.py
tests/test_search.py
tests/test_util_owsutil.py

This PR adds an additional search parameter to limit the number of WFS features, see #184

Maxfeatures

---

setup.py

Promote to beta.

---

pydov/util/query.py
tests/abstract.py
tests/test_search_boring.py
tests/test_search_grondmonster.py
tests/test_search_grondwaterfilter.py
tests/test_search_grondwatermonster.py
tests/test_search_itp_formelestratigrafie.py
tests/test_search_itp_gecodeerdelithologie.py
tests/test_search_itp_geotechnischecodering.py
tests/test_search_itp_hydrogeologischestratigrafie.py
tests/test_search_itp_informelehydrogeologischestratigrafie.py
tests/test_search_itp_informelestratigrafie.py
tests/test_search_itp_lithologischebeschrijvingen.py
tests/test_search_itp_quartairstratigrafie.py
tests/test_search_sondering.py

Add tests and fix PropertyInList and Join operators.
Closes #212

Fix PropertyInList and Join operators

---

.github/CONTRIBUTING.rst

This PR extends the developer documentation explaining the usage of our multiple `requirement_*.txt` files and explaining to new developers to get a development environment setup.

Fix #86 by adding documentation on dev environment

---

README.md
docs/quickstart.rst

This is part of https://github.com/DOV-Vlaanderen/pydov/pull/228 rebased against master
(the documentation updates).

Update bounding box

---

AUTHORS.rst

Describe your fixes/additions/changes

Add Joris Synaeve to Author list.

---

pydov/search/abstract.py
pydov/util/caching.py
pydov/util/location.py
pydov/util/owsutil.py
setup.py
tests/abstract.py
tests/test_encoding.py
tests/test_search.py
tests/test_util_caching.py
tests/test_util_owsutil.py

This is a rebased version of https://github.com/DOV-Vlaanderen/pydov/pull/228

Remove py2

---

pydov/util/owsutil.py

This used to be here but got accidentally removed in #238.

Ignore FutureWarning from OWSLib.

---

docs/notebooks/search_grondwaterfilters.ipynb

Describe your fixes/additions/changes
I have fixed the typo that was highlighted in the issue https://github.com/DOV-Vlaanderen/pydov/issues/258

Fixed typo in tutorial

---

docs/development.rst

This PR updates the documentation file on the different requirement files as note in #293. It does not merge existing requirements files or decreases the number of files.

Update requirements file overview

---

docs/installation.rst

Fix issue #304 by fixing typo

---

docs/quickstart.rst

Small fix to the documentation: add GrondwaterVergunning to quickstart.

Add GrondwaterVergunning to quickstart.

---

.github/workflows/ci.yml

Enable CI on pull requests to branches as well

Enable CI on pull requests to branches as well

---

docs/output_fields.rst

* [x ] I have read and followed the guidelines in the `CONTRIBUTING` document
* [x ] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x ] I have updated the documentation accordingly.
* [x ] All new and existing tests passed.
Documentation branch for the bodem objects.

Bodemdata documentation

---

docs/output_fields.rst

Translate Bodem objecttypes in default output fields documentation.

Translate Bodem objecttypes in default output fields documentation.

---

docs/development.rst
docs/installation.rst
docs/notebooks/spatial_querying.ipynb

Small fixes in the documentation, including some Markdown to RST formatting and typos.

Small documention fixes.

---

tests/test_util_hooks.py

Fix the inject hook test that started failing when the 'gemeente' of the test Boring was removed in oefen.

Fix inject hook test.

---

tests/test_types_pluggable.py

Add test fixtures for test_types_pluggable.

---

docs/installation.rst
docs/network_proxy.rst

Some clarification on installing pydov with proxy autodiscovery support, especially on Windows.

Update proxy documentation.

---

pydov/search/abstract.py
pydov/util/location.py

Distutils will be deprecated in Python 3.12

Replace distutils package

---

requirements.txt
tests/data/update_test_data.py

The new OWSLib release fixes the pyproj dependecy, so we can remove our tricks.
Also includes a small fix in the testdata update script.

Update OWSLib dependency

---

pydov/search/abstract.py
tests/data/wfs_paging/wfsgetfeature_0.xml
tests/data/wfs_paging/wfsgetfeature_1.xml
tests/test_search_wfs_paging.py

When requesting max_features that is larger than the WFS page size, we should respect the max_features in the paged requests too and possibly limit the last of the paged requests as well.

Respect max_features in paged WFS requests too.

---

requirements_vectorfile.txt

Recent Fiona release adds Windows wheels too, so no need to use alpha version.

Switch back to Fiona release

---

pydov/search/abstract.py
pydov/util/errors.py
tests/data/date/feature.xml
tests/data/date/wfsgetfeature.xml
tests/test_date.py

Replace unparseable data from DOV with NaN and issue a warning.
Closes #368

Replace unparseable data by nan and issue a warning. - backport to 2.2.x

---

tox.ini

Fix documentation build on tox.

Fix documentation build on tox.

---

pydov/search/abstract.py
tests/test_search.py

Update parsing of datetime fields. This relates to #348, as this introduces datetime field(s).

Update parsing of datetime fields.

---

pydov/search/abstract.py
pydov/types/abstract.py
pydov/types/fields.py
pydov/types/interpretaties.py
tests/test_search_customfield.py
tests/test_search_itp_informelestratigrafie.py

Refactor custom WFS fields and make sure they resolve in all circumstances. Closes #379

Refactor custom fields

---

contrib/PFAS_concentrations/PFAS_concentrations.py
contrib/PFAS_concentrations/PFAS_concentrations_tutorial.ipynb
contrib/PFAS_concentrations/README.md

To the PFAS contribution file I added the options to combine the data of the same matrix and save in an extra tab of the output Excel file.

Combine PFAS data of the same matrix

---

.github/workflows/ci.yml
docs/reference.rst
pydov/search/abstract.py
pydov/types/abstract.py
pydov/types/boring.py
pydov/types/fields.py
pydov/types/grondwaterfilter.py
pydov/types/interpretaties.py
pydov/types/ligging.py
pydov/types/sondering.py
pydov/util/owsutil.py
tests/abstract.py
tests/test_types_ligging.py

Update the `mv_mtaw` fields of Boring, Sondering and Grondwaterfilter to prepare for the upcoming changes in the DOV XML schema (while still supporting the current schema too).

Update mv_mtaw fields based on updated DOV XML schema

---

pydov/types/ligging.py
tests/test_types_ligging.py

Commit all changes and fix test.

Update mv_mtaw fields based on updated DOV XML schema (fixes)

---

contrib/PFAS_concentrations/PFAS_concentrations.py
contrib/PFAS_concentrations/PFAS_concentrations_tutorial.ipynb
contrib/PFAS_concentrations/README.md

Added the option to download the PFAS air data. Adapted the corresponding documentation and tutorial.
Made also some minimal changes to download the 'combined_soil' data (give the data records a unique ID)

Download PFAS air data + few adjustments.

---

docs/output_fields.rst
docs/reference.rst
docs/select_datasets.rst
docs/tutorials.rst
pydov/types/observatie.py
tests/data/update_test_data.py
tests/test_search_monster.py
tests/test_search_observatie.py
tests/test_types_monster.py
tests/test_types_observatie.py

Some small fixes after integrating generic monster and observation types.

Small fixes after merging generic monster and observations

---

docs/select_datasets.rst
pydov/types/monster.py
tests/test_types_monster.py

* [] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
Adding subtype opslaglocatie

Add subtype Opslaglocatie for Monster type

---

docs/notebooks/search_observaties.ipynb
docs/select_datasets.rst
pydov/types/observatie.py
tests/data/update_test_data.py
tests/test_search_observatie.py
tests/test_types_observatie.py

Adding 'herhalingen' to observations

 Add subtype ObservatieHerhaling for Observatie type
