DOV-Vlaanderen/pydov

requirements_dev.txt, tox.ini
Try to fix documentation build on ReadTheDocs.
Add all requirements to requirements_dev, since ReadTheDocs only allows one requirements file and we need installtime requirements too to be able to import the modules to build their documentation.
=> Fix Readthedocs

pydov/search.py, tests/test_search.py
I added validation on the query parameter type, so we prevent vague xml exceptions and present the user with a more meaningful error.
=> Validate the type of query parameter.

examples/boring_search.py, pydov/search.py, pydov/util/owsutil.py, requirements.txt, tests/test_search.py, tests/test_util_owsutil.py
This enables the combination of a geographical and attribute query in
one search operation and opens the door to support geometries beyond
simple bounding boxes in the future.
Closes #46
=> Add support for WFS GetFeature via POST.

pydov/types/abstract.py, pydov/util/owsutil.py, tests/abstract.py, tests/test_encoding.py
Fixes issue #69 regarding encoding issues with the WFS GetFeature call, both in Python2.7 and Python3.
Includes an online test for the issue, in favor of offline tests using monkeypatching. This to avoid testing the encoding of our testdata and patching implementation..
=> Fix encoding issue in WFS GetFeature

appveyor.yml
Add `--ignore-installed` in appveyor.yml to fix Anaconda build.
=> Fix Anaconda build in AppVeyor.

pydov/types/abstract.py, tests/test_search_boring.py, tests/test_search_grondwaterfilter.py
Fix the use of fields from subtypes as return fields.
Closes #78
=> Fix using fields from a subtype as return fields.

docs/df_format.rst
Minimal fix to make sure the table of boreholes: https://pydov.readthedocs.io/en/documentation/df_format.html#boreholes-in-dutch-boring is rendered properly
=> Fix rendering borehole format table

pydov/types/abstract.py, pydov/util/caching.py, pydov/util/dovutil.py, pydov/util/errors.py, pydov/util/owsutil.py, tests/data/encoding/invalidcharacters.xml, tests/test_encoding.py
If the user has lxml installed, we try parsing the XML documents with the 'recover' option to parse even invalid documents.
If lxml is not installed we have to rely on the default Python XML library which does not support the 'recover' option. In this case we cannot parse invalid XML documents and have to set the dataframe columns relying on XML information to 'nan'. We warn the user that the returned dataframe is incomplete.
Closes #110
=> Fix crash when XML document is invalid

pydov/search/abstract.py, pydov/util/caching.py
To align with other PyDOV requests using WFS version 1.1.0, we should request the schema (i.e. WFS DescribeFeatureType) in version 1.1.0 too instead of the default 1.0.0.
Also: rewrite the type_key regex to comply with new warnings (W605 invalid escape sequence) in flake8 3.6.0
=>  Request remote schema in WFS version 1.1.0. 

appveyor.yml, requirements_appveyor.txt
Install owslib (and as a consequence: pyproj) with conda instead of pip to avoid compilation error.
Closes #157
=> Appveyor: install owslib (and pyproj) with conda.

docs/caching.rst, docs/notebooks/caching.ipynb, pydov/__init__.py, pydov/util/caching.py, tests/test_encoding.py, tests/test_util_caching.py, tests/test_util_hooks.py
Introduce GzipTextFileCache that uses GZIP to compress cached XML documents. These take up to 1/10th the size of plain text documents.
The old implementation using plain text is still available as PlainTextFileCache.
Introduce AbstractCache for anyone wanting to implement their own caching system.
Closes #131
=> Use gzip to compress cached xml files

tests/test_search.py
Should fix tests on Python3 on Windows.
Closes #173
=> Add encoding parameter to monkeypatches reading XML/XSD files.

pydov/util/query.py, tests/test_util_query.py
Support PropertyInList with a single-element list and Join with a dataframe containing a single not-null value in the `using` column.
Closes #206
=> Add support to Join with a dataframe containing a single element too

appveyor.yml, requirements.txt
OWSLib 0.19.0 (released last week) dropped support for Python2. Since we don't pin versions in the requirements file, pydov's Travis is failing on Python2 now. Same goes for pandas and numpy, who have dropped support for Python2 in their latest releases.
In order to release a final 1.0.0 of pydov which is still Python2 compatible, I suggest pinning:
* owslib<0.19.0
* pandas<0.25.0
* numpy<1.17.0
Closes #215
=> Pin requirements to keep Python2 support.

pydov/__init__.py
Increase the default request timeout to 5 minutes instead of 1, to align
with the reverse proxy settings serverside.
This allows executing larger WFS queries in pydov.
Closes #217
=> Increase request timeout to 5 minutes.

docs/output_fields.rst, pydov/types/grondwaterfilter.py, tests/test_search_grondwaterfilter.py
The meetnet_code XML attribute of the GrondwaterFilter type should be of type 'string' instead of 'integer'.
The next release of the DOV XML schema introduces "meetnet 20 – eDOV erkende boorbedrijven" with code edov.
Closes #219
=> Make meetnet_code a string.

appveyor.yml, requirements.txt
Since python 2 support is removed, those pins can be relaxed again I think.
=> Remove pins in the requirements

docs/hooks.rst, pydov/__init__.py, pydov/search/abstract.py, pydov/types/abstract.py, pydov/util/caching.py, pydov/util/dovutil.py, pydov/util/hooks.py, pydov/util/owsutil.py, tests/conftest.py, tests/test_util_hooks.py
In preparation of the repeatable logging implementation, this PR refactors and extends the hooks system. They are split into two base classes: AbstractReadHook for (safe) read-only hooks and AbstractInjectHook that interferes with pydov's execution stack and should be used in rare cases only.
Some hooks are removed: `xml_requested `is replaced with `xml_received`, while new hooks include:
* `meta_received` and `inject_meta_response`,
* `wfs_search_result_received ` and `inject_wfs_getfeature_response`,
* `xml_received` and `inject_xml_response`.
This allows saving the metadata, wfs and xml results and reinjecting (replaying) them later.
Also centralises hook execution into a common HookRunner class (this is pydov internal code and does not affect hook implementations).
=> Refactor and extend hooks system

tests/abstract.py
Since we only rely on the status code and the headers to determine if a
service is working or not, it is not needed to perform a GET (resulting
in downloads of data we don't need).
Instead we could use a HEAD request. Since Requests does not follow
redirects by default when using HEAD [1], we enable it explicitly using
allow_redirects.
Also update to use the global pydov requests session instead of creating
a new one for each call.
[1]: https://2.python-requests.org/en/master/user/quickstart/#redirection-and-history
=> Tests: use HEAD instead of GET in service_ok

pydov/util/location.py, pydov/util/owsutil.py, pydov/util/query.py, tests/test_util_location_gmlfilter.py, tests/test_util_owsutil.py, tests/test_util_query.py
This PR updates some internals regarding generation of WFS GetFeature requests in order for them to become stable (i.e. generating the same GetFeature request when given the same input data/filters).
This is important for implementing repeatable logging for this relies on generating stable hashes of these requests to be able to identify and replay previously recorded WFS calls.
Mind that this does not mean the current implementation of WFS GetFeature is broken: it is entirely possible for two GetFeature requests to yield the same results while the requests are not exactly identical.
Three cases are covered in this PR: (1) the order of the PropertyNames to be retrieved in the result, (2) the order of PropertyIsEqualTo filters generated by PropertyInList and (3) the order of spatial filters …
=> Generate stable WFS GetFeature requests

pydov/search/abstract.py, pydov/search/boring.py, pydov/search/grondmonster.py, pydov/search/grondwaterfilter.py, pydov/search/grondwatermonster.py, pydov/search/interpretaties.py, pydov/search/sondering.py
This PR switches to workspace-level WFS endpoints for accessing the DOV feature types.
This change will benefit download size (and times) of the WFS capabilities, since the workspace-level endpoints will be a lot smaller than the main DOV WFS endpoint which now has over 2300 feature types.
As a result a lot of common code can also be removed: as there remains no large static data to share between search objects, more code can be moved into the abstract base class.
Closes #281
Closes #264
=> Switch to workspace-level WFS endpoints

docs/output_fields.rst, pydov/types/sondering.py, tests/test_search_sondering.py, tests/test_types_sondering.py
This PR adds:
* the `sondeernummer` field to the documentation of the Sondering type
* the `mv_mtaw` field to the Sondering type and the documentation
Closes #289
=> Add missing Sondering fields

.readthedocs.yml, docs/conf.py, readthedocs.yml
Update the ReadTheDocs config. Currently builds are failing because docs are built with Python3.7 and pandas 1.4.0 only supports Python3.8+
=> Update ReadTheDocs config.

tests/test_search_grondmonster.py
A change in the rounding of observation values in the XML export causes a test failure on the 'oefen' environment. Adjusted the test to ignore the rounding of values (the test is mostly there to check if the values are not NaN).
=> Fix test failure due to rounding.

.github/workflows/ci.yml, docs/installation.rst, docs/network_proxy.rst, requirements.txt, requirements_vectorfile.txt, tox.ini
This PR fixes the build by switching to the new Fiona 1.9 (alpha for now) that has binary wheel available for Windows too.  This way we can also remove the pipwin installed wheels whose future is unsure.
Also we pin OWSLib to a version before 0.26 on Python >= 3.10, since 0.26 depends on an old pyproj that has no binary wheels for recent Python versions. Hopefully this will be fixed in a future OWSLib version.
=> Fix CI build

pydov/util/owsutil.py, tests/conftest.py, tests/test_util_owsutil_no_mp.py
Currently this leads to an (ugly) AttributeError (see #355), while we have MetadataNotFoundError for cases like this.
=> Raise MetadataNotFoundError when remote metadata fails to be downloaded or parsed.

pydov/util/net.py, setup.cfg
Universal wheels are for Python2 and Python3, and we're no longer supporting Python2 for quite a while now.
=> Don't build universal wheels as we're Py3 only these days.

.github/workflows/ci.yml, .github/workflows/pypi.yml, HISTORY.rst, setup.py, tox.ini
Python 3.7.15 includes an upgrade of libexpat which appears to break some XML parsing functionality. We will not investigate this further and drop support for Python3.7 from pydov 3.0.0 onwards. Recent pandas already dropped support for Python3.7 some time ago.
=> Drop support for Python3.7

pydov/util/dovutil.py
Following the 0.28.1 OWSLib security release, also disable XML entity resolving when using lxml's XMLParser in pydov.
This is the backport for the 2.2 branch.
=> Disable XML entity resolving in lxml. (backport to 2.2.x)

tox.ini
Since OWSLib requires lxml from 0.28.1 onwards, we can remove the `nolxml` test environments from CI.
=> Remove nolxml test environments from CI.

pydov/util/location.py, pydov/util/owsutil.py, tests/test_util_location.py, tests/test_util_owsutil.py
Generate stable and unique GML ids for Box and Point locations.
Closes #387
=> Generate stable and unique GML ids for Box and Point locations.

pydov/search/abstract.py, tests/abstract.py, tests/conftest.py, tests/test_search_wfs_paging.py
This PR fixes property name replacement in the sort_by clause of a search query. It also refactors the test fixtures to function scope (instead of module scope) to be able to expose the problem in tests.
Closes #390
=> Fix property name replacement in sort_by.

.github/CONTRIBUTING.rst, contrib/README.md
Add some documentation for the contrib section.
=> Add some documentation for the contrib section.

tests/test_util_location.py
Since the Boring XML export now encodes the location as GML, we can no longer use it as an invalid GML. Switch to Interpretatie XML that contains no location at all, so will definitely be invalid GML.
=> Fix GMLObject tests.

docs/query_attribute.rst, pydov/util/query.py, tests/test_util_query.py
Introduce PropertyLikeList and FuzzyJoin query utilities to search for, and join on, fuzzy (non-exact) matches.
This is part of upcoming changes for the Grondmonster type, where a Grondmonster will (possibly) have multiple parents.
This change will allow to search on the aggregated field of the new Grondmonster service with another output dataframe with pkey's, using the new FuzzyJoin operator.
=> Introduce PropertyLikeList and FuzzyJoin query utilities.

pydov/types/abstract.py, pydov/types/fields.py, pydov/types/interpretaties.py, tests/abstract.py
This is part of upcoming changes for the Grondmonster type, where a Grondmonster will (possibly) have multiple parents.
This change will allow to parse the contents of the aggregated field into a list of separate pkey's in the output dataframe. Which in turn will allow to use this output dataframe as input for further searches using e.g. a Join operator.
=> Add support for splitting field values into a list of values.

pydov/util/owsutil.py, tests/test_search_boring.py, tests/test_util_owsutil.py
Always request geometry using urn:ogc: srsName to fix coordinate ordering.
=> Always request geometry using urn:ogc: srsName to fix coordinate ordering

HISTORY.rst, pydov/util/owsutil.py, tests/test_search_boring.py, tests/test_util_owsutil.py
Backport the coordinate order fix to 3.3.0 branch
=> Fix coordinate order (backport to 3.3.0)
